In [1]:
import numpy as np
import pandas as pd
import scipy
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler

In [2]:
dados = scipy.io.loadmat(r"C:\Users\boave\OneDrive\Desktop\Pasta Pessoal - Boaventura Filho\PIBIC\Dados\barra_6kv_condi_1")

In [3]:
dados.values()

dict_values([b'MATLAB 5.0 MAT-file, Platform: PCWIN64, Created on: Fri Oct 25 09:54:30 2024', '1.0', [], array([[ 1.26266406e-01,  1.07125781e-01,  9.69695313e-02, ...,
         1.34078906e-01,  1.22164844e-01,  1.38571094e-01],
       [ 2.42780885e+01,  4.71812595e+01,  7.35990319e+01, ...,
         2.06046990e+02,  2.27669605e+02,  2.49815282e+02],
       [ 1.77637807e-02,  2.64073337e-02,  2.51448184e-02, ...,
         1.96421184e-02,  7.16884847e-03,  1.33674614e-02],
       ...,
       [ 1.77637807e-02,  1.18216758e-02,  2.71589820e-02, ...,
         1.23586275e-02,  8.76761038e-03,  2.09166100e-03],
       [ 1.93106094e-02, -9.40774910e-04,  7.01734600e-03, ...,
         3.61843832e-03, -8.24961128e-04,  6.32008617e-03],
       [ 1.77637807e-02,  4.52884681e-03,  1.70881640e-02, ...,
        -3.66505262e-03,  1.35638961e-02,  1.61864116e-02]],
      shape=(403, 52))])

In [4]:
df = pd.DataFrame(list(dados.values())[-1])
df

,0,1,2,3,4,5,6,7,8,9,...,42,43,44,45,46,47,48,49,50,51
0,0.126266,0.107126,0.096970,0.111032,0.145798,0.116891,0.103610,0.098727,0.150290,0.132712,...,0.133102,0.108688,0.097165,0.099509,0.119235,0.105173,0.118454,0.134079,0.122165,0.138571
1,24.278088,47.181260,73.599032,203.379397,223.703278,248.527455,32.626977,52.742221,214.536815,236.797458,...,265.587097,20.008590,40.848259,55.651693,28.259999,48.991628,76.367047,206.046990,227.669605,249.815282
2,0.017764,0.026407,0.025145,0.009647,0.016724,0.022530,0.017878,0.028654,0.009726,0.015429,...,0.031525,0.018840,0.037155,0.008801,0.017173,0.019469,0.002447,0.019642,0.007169,0.013367
3,0.025498,0.019115,0.023131,0.027237,0.011365,0.014176,0.014108,0.014806,0.009726,0.009543,...,0.005112,0.018840,0.015044,0.020578,-0.000845,0.015755,0.009042,0.022556,0.021558,0.016186
4,0.013123,0.017291,0.025145,0.011406,0.018063,0.000809,0.025418,0.008871,0.012325,0.008071,...,0.006580,0.011652,0.004993,0.012727,0.022087,0.010184,0.022233,0.015272,0.010366,0.013367
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
398,0.022404,0.020938,0.009032,0.021960,0.007346,0.019188,0.014108,0.036567,0.012325,0.009543,...,0.021254,-0.006318,0.025094,0.014689,-0.004121,0.019469,0.023882,0.010902,0.015163,0.013367
399,0.005389,0.013645,-0.001039,0.018442,0.006007,0.012505,0.015993,0.024697,0.001929,0.013958,...,0.005112,0.008058,0.013034,0.012727,0.007345,0.021327,0.018935,0.022556,0.011965,0.013367
400,0.017764,0.011822,0.027159,0.013165,0.015384,0.000809,0.021648,0.026675,0.004528,0.011014,...,0.006580,-0.002724,0.013034,0.012727,0.018811,0.006470,0.013989,0.012359,0.008768,0.002092
401,0.019311,-0.000941,0.007017,0.004370,0.016724,0.020859,0.012223,0.008871,0.011026,0.005127,...,0.021254,0.015246,0.013034,0.014689,0.013897,0.010184,0.010691,0.003618,-0.000825,0.006320
402,0.017764,0.004529,0.017088,0.030755,0.012705,0.019188,0.008453,0.022719,0.013625,0.009543,...,0.010982,0.013449,0.033135,0.014689,0.007345,0.026898,0.015638,-0.003665,0.013564,0.016186

In [5]:
# Criar a coluna de classe
df.loc['classe'] = ['positivo' if valor <= 180 else 'negativo' for valor in df.iloc[1, :]]

In [6]:
# Filtrar os elementos do semi-ciclo positivo
dados_sp = df.loc[:, df.loc['classe'] == 'positivo'].drop('classe').to_numpy()[:2, :]
dados_sp = dados_sp.astype(float)  # Garantir que todos os elementos sejam floats
dados_sp.shape

(2, 29)

In [7]:
# Filtrar elementos do semi-ciclo negativo
dados_sn = df.loc[:, df.loc['classe'] == 'negativo'].drop('classe').to_numpy()[:2, :]
dados_sn = dados_sn.astype(float)  # Garantir que todos os elementos sejam floats

In [8]:
#Produzir a matriz de PRPD geral
matrix = np.array(list(dados.values())[-1])
PRPD = matrix[:2, :]
PRPD.shape

(2, 52)

In [9]:
#Normalizar os vetores de amplitudes dos semi-ciclos:
dados_sn[0,:] = dados_sn[0,:]/max(dados_sn[0,:])
dados_sp[0,:] = dados_sp[0,:]/max(dados_sp[0,:])

In [10]:
class PRPDMetrics():

    def __init__(self, PRPD: np.ndarray):
        """
        Inicializa a classe com um array.

        Args:
            PRPD(ndarray): Array NumPy contendo valores de amplitude e fase.
        """

        if not isinstance(PRPD, np.ndarray): # Validações de entrada
            raise TypeError("PRPD deve ser um array NumPy.")
        if PRPD.size == 0:
            raise ValueError("PRPD não pode ser vazio.")
        
        self.PRPD = PRPD # Normaliza os dados
        self._minimum = None # prefixo _ indica que são variáveis internas (convenção Python)
        self._maximum = None
        self._elements = None
        self._mean = None
        self._Firstquartile = None
        self._Secondquartile = None
        self._Thirdquartile = None
        self._Assymetry = None
        self._Kurtosis = None
        self._dataframe = None

    @property # permite acessar o método como se fosse um atributo (sem parênteses)
    def minimum(self) -> float:
        """Calcula e retorna o valor minimo dos vetores de amplitudes e fases"""
        if self._minimum is None:
            self._minimum = np.min(self.PRPD, axis=1)
        return self._minimum
    
    @property
    def maximum(self) -> float:
        """Calcula e retorna o valor maximo dos vetores de amplitude e fase"""
        if self._maximum is None:
            self._maximum = np.max(self.PRPD, axis=1)
        return self._maximum
    
    @property
    def elements(self) -> float:
        """Calcula e retorna a quantidade de pulsos"""
        if self._elements is None:
            self._elements = PRPD.shape[1]
        return self._elements
    
    @property
    def mean(self) -> float:
        """Calcula e retorna a media dos amplitudes e fases"""
        if self._mean is None:
            self._mean = np.mean(self.PRPD, axis=1)
        return self._mean
    
    @property
    def firstquartile(self) -> float:
        """Calcula e retorna o primeiro quartil das amplitudes e fases"""
        if self._Firstquartile is None:
            self._Firstquartile = np.percentile(self.PRPD, 25, axis=1)
        return self._Firstquartile
    
    @property
    def secondquartile(self) -> float:
        """Calcula e retorna o segundo quartil das amplitudes e fases"""
        if self._Secondquartile is None:
            self._Secondquartile = np.percentile(self.PRPD, 50, axis=1)
        return self._Secondquartile
    
    @property
    def thirdquartile(self) -> float:
        """Calcula e retorna o terceiro quartil das amplitudes e fases"""
        if self._Thirdquartile is None:
            self._Thirdquartile = np.percentile(self.PRPD, 75, axis=1)
        return self._Thirdquartile
    
    @property
    def assymetry(self) -> float:
        """Calcula e retorna o assimetria das amplitudes e fases"""
        if self._Assymetry is None:
            self._Assymetry = scipy.stats.skew(self.PRPD, axis=1)
        return self._Assymetry
    
    @property
    def kurtosis(self) -> float:
        """Calcula e retorna a curtose das amplitudes e fases"""
        if self._Kurtosis is None:
            self._Kurtosis = scipy.stats.kurtosis(self.PRPD, axis=1)
        return self._Kurtosis  
    
    @property
    def dataframe(self) -> pd.DataFrame:
        """Retorna um DataFrame com todas as métricas calculadas"""
        if self._dataframe is None:
            self._dataframe = pd.DataFrame({
                'Minimum': self.minimum,
                'Maximum': self.maximum,
                'Elements': self.elements,
                'Mean': self.mean,
                'First Quartile': self.firstquartile,
                'Second Quartile': self.secondquartile,
                'Third Quartile': self.thirdquartile,
                'Assymetry': self.assymetry,
                'Kurtosis': self.kurtosis}, 
                index = ['Amplitude', 'Fase'])
        return self._dataframe

In [11]:
#Atribuindo a classe a um objeto e avaliando seu dictionary:

metrics_sp = PRPDMetrics(dados_sp)
metrics_sn = PRPDMetrics(dados_sn)

metrics_sn.__dict__

{'PRPD': array([[  0.68042476,   0.89347492,   0.71633209,   0.92100387,
           0.81328188,   0.90305021,   0.63135141,   0.72231665,
           0.95930503,   0.8479923 ,   0.97366796,   0.717529  ,
           1.        ,   0.97127414,   0.79772204,   0.95930503,
           0.81088806,   0.61459465,   0.75702706,   0.8156757 ,
           0.82166026,   0.74864869,   0.84918921],
        [203.37939702, 223.70327762, 248.52745473, 214.53681495,
         236.79745751, 210.20585094, 230.55881933, 202.48373551,
         225.77439746, 243.84657153, 208.60411798, 230.50756941,
         211.5641468 , 235.3823712 , 205.36965972, 229.47945458,
         264.01600983, 206.08681224, 231.99364378, 265.58709672,
         206.04698967, 227.66960542, 249.81528196]]),
 '_minimum': None,
 '_maximum': None,
 '_elements': None,
 '_mean': None,
 '_Firstquartile': None,
 '_Secondquartile': None,
 '_Thirdquartile': None,
 '_Assymetry': None,
 '_Kurtosis': None,
 '_dataframe': None}

In [12]:
#Salvando o Dataframe com as features em um csv
df_sp = metrics_sp.dataframe.T
df_sp.to_csv('PRPDfeatures_sp_barra_6kv_condi_1.csv',index = True)

df_sn = metrics_sn.dataframe.T
df_sn.to_csv('PRPDfeatures_sn_barra_6kv_condi_1.csv',index = True)

df_sn

                 Amplitude        Fase
Minimum           0.614595  202.483736
Maximum           1.000000  265.587097
Elements         52.000000   52.000000
Mean              0.822857  226.605936
First Quartile    0.735483  209.404984
Second Quartile   0.815676  227.669605
Third Quartile    0.912027  236.089914
Assymetry        -0.125541    0.500099
Kurtosis         -0.972562   -0.651366

In [13]:
df_sp

                 Amplitude       Fase
Minimum           0.659698  18.125502
Maximum           1.000000  76.367047
Elements         52.000000  52.000000
Mean              0.827449  43.576051
First Quartile    0.767976  24.961132
Second Quartile   0.806646  43.053910
Third Quartile    0.911831  55.651693
Assymetry         0.229791   0.176098
Kurtosis         -0.835876  -1.120394

In [ ]:
#Analisando se os arquivos estão ok e se as features estão corretas
df_sp = pd.read_csv('PRPDfeatures_sp_barra_6kv_condi_1.csv')
df_sn = pd.read_csv('PRPDfeatures_sn_barra_6kv_condi_1.csv')

df_sp

        Unnamed: 0  Amplitude       Fase
0          Minimum   0.659698  18.125502
1          Maximum   1.000000  76.367047
2         Elements  52.000000  52.000000
3             Mean   0.827449  43.576051
4   First Quartile   0.767976  24.961132
5  Second Quartile   0.806646  43.053910
6   Third Quartile   0.911831  55.651693
7        Assymetry   0.229791   0.176098
8         Kurtosis  -0.835876  -1.120394

In [15]:
df_sn

        Unnamed: 0  Amplitude        Fase
0          Minimum   0.614595  202.483736
1          Maximum   1.000000  265.587097
2         Elements  52.000000   52.000000
3             Mean   0.822857  226.605936
4   First Quartile   0.735483  209.404984
5  Second Quartile   0.815676  227.669605
6   Third Quartile   0.912027  236.089914
7        Assymetry  -0.125541    0.500099
8         Kurtosis  -0.972562   -0.651366